[package]
name = "orion-scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
qlean = { git = "https://github.com/buck2hub/qlean" }
tokio = { version = "1.52.3", features = ["macros", "rt"] }

# HTTP server
axum = { version = "0.8.9", features = ["macros"] }
tower = "0.5.3"
tower-http = { version = "0.6.11", features = ["cors", "trace"] }
hyper = "1.3"
http-body-util = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3"
futures-util = "0.3"
async-stream = "0.3"
sha2 = "0.11.0"

[dev-dependencies]
anyhow = "1.0.102"
